## How to determine the distances between H and O atoms in a water molecule

In [14]:
import os
import numpy

In [15]:
file_location=os.path.join('data','water.xyz')
xyz_file=numpy.genfromtxt(fname=file_location, skip_header=2,dtype='unicode')
print(xyz_file)
#unicode means mixed data = strings and floats
#when you use numpy.genfromtxt, output is in a matrix or numpy array (you must have same number of columns in every row)
#alternate method is readlines() but that method is not that sophisticated

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [16]:
symbols = xyz_file[:,0]
#[:,:] means every row, every column
#[:,0] means every row, first/leftmost column only
#[:,1:] means every row, column index 1 (2nd column) to the end
coordinates = (xyz_file[:,1:])
print(symbols)
print(coordinates)

['O' 'H1' 'H2']
[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [17]:
#recast coordinates into floats
#astype means assign type
coordinates = coordinates.astype(numpy.float)
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [18]:
#note that distance formula is markdown and needs $$ on both sides $$
#I am at 18:28 in Session 3 video but I need to go back to Session 2 video starting at 1:19:26

$$ distance = \sqrt(x1-x2)^2 +(y1-y2)^2 + (z1-z2)^2) $$

In [28]:
num_atoms = len(symbols)
#num_atoms should equal 3
print(num_atoms)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1 < num2:
            x_distance=coordinates[num1,0]-coordinates[num2,0]
            y_distance=coordinates[num1,1]-coordinates[num2,1]
            z_distance=coordinates[num1,2]-coordinates[num2,2]
            bond_length_12=numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
            if bond_length_12 > 0 and bond_length_12 <= 1.5:
                print(F'{symbols[num1]} to {symbols[num2]}: {bond_length_12:.3f}')

    #In the last line, I don't know what capital F mean and I don't know what 3f means
    #In Session 3 video around 29 min, Ashley says this is called F printing
    #the .3f at the end formats the number of decimal places that I print (but it does not round, just truncates)

3
O to H1: 0.969
O to H2: 0.969
